server:
  port: 0
spring:
  application:
    name: user-center
  datasource:
    url: jdbc:mysql://47.96.25.247:3306/user_center
    hikari:
      username: root
      password: abc.123
      driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        # 指定nacos server的地址
        server-addr: localhost:8848
        namespace: 40190c4b-cc61-43c5-8431-cec135e10151
        metadata:
          instance: cc
          version: 1.0

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
rocketmq:
  name-server: 47.96.25.247:9876
