server:
  port: 8002
spring:
  application:
    name: content-center
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:mysql://47.96.25.247:3306/content_center?serverTimezone=Asia/Shanghai&characterEncoding=utf-8
    hikari:
      username: root
      password: abc.123
      driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        # 指定nacos server的地址
        server-addr: localhost:8848
        namespace: 40190c4b-cc61-43c5-8431-cec135e10151

    sentinel:
      transport:
        dashboard: localhost:8080

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

#user-center:
#  ribbon:
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule

ribbon:
  eager-load:
    enabled: true
    clients: user-center

rocketmq:
  name-server: 47.96.25.247:9876
  producer:
    group: test-group

## feign细粒度配置
#feign:
#  client:
#    config:
#      #想要调用的微服务名称
#      user-center:
#        loggerLevel: full

# feign细粒度配置
#feign:
#  client:
#    config:
#      #想要调用的微服务名称
#      default:
#        loggerLevel: full