server:
  port: 8082
spring:
  application:
    name: course-center
  datasource:
    url: jdbc:mysql://47.96.25.247:3306/course_center
    hikari:
      username: root
      password: abc.123
      driver-class-name: com.mysql.cj.jdbc.Driver

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always